# Site settings
title: English Camp
description: "Thinker // Designer // Youtuber"
email: artist@email


avatar: face1.jpg
blurb: <p><strong>Anton specializes in making things</strong> for human people. Most of the things he makes are <a href="http://google.com">digital interfaces</a>, but he also puts effort into crafting next-level beats and YouTube videos about making codes happen.</p>

# Build settings
markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :compressed